// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4p79FgKb6vMqc7jm9ZZ8YZGgAeecJN4M',
    appId: '1:687273347221:web:095553b5998e2486be739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    authDomain: 'cleanmatch-a0361.firebaseapp.com',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    measurementId: 'G-JWPMMPD8E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQqQo0aLZ-9oL2XP1CSYvSybrbkeChmY',
    appId: '1:687273347221:android:976de1385e163dc1be739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWyRT0uk-4lDoVf9rWGE2uee6ec1S2WM',
    appId: '1:687273347221:ios:2094f9e44ff05010be739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    iosBundleId: 'com.example.worker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWyRT0uk-4lDoVf9rWGE2uee6ec1S2WM',
    appId: '1:687273347221:ios:2094f9e44ff05010be739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    iosBundleId: 'com.example.worker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4p79FgKb6vMqc7jm9ZZ8YZGgAeecJN4M',
    appId: '1:687273347221:web:3937898091eb3e54be739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    authDomain: 'cleanmatch-a0361.firebaseapp.com',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    measurementId: 'G-8E45CJ9L25',
  );

}